-- =============================================
-- Seed Data - Timoneiro - Jompastech
-- =============================================

-- OBS.: Users need to be inserted manually because of the crypted password generated by the back end


-- ADDRESSES
INSERT INTO addresses (cep, number, street, neighborhood, city, state) VALUES
('22041-001', '100', 'Avenida Atlântica', 'Copacabana', 'Rio de Janeiro', 'RJ'),
('22451-001', '200', 'Avenida Vieira Souto', 'Ipanema', 'Rio de Janeiro', 'RJ'),
('28950-000', 'S/N', 'Estrada do Contorno', 'Centro', 'Búzios', 'RJ'),
('11680-000', '50', 'Avenida da Praia', 'Centro', 'Ubatuba', 'SP'),
('11695-000', '120', 'Rua das Embarcações', 'Itaguá', 'Ubatuba', 'SP'),
('28970-000', '300', 'Avenida do Mar', 'Centro', 'Arraial do Cabo', 'RJ'),
('23900-000', '75', 'Rua da Praia', 'Mambucaba', 'Angra dos Reis', 'RJ'),
('11600-000', '25', 'Avenida Beira Mar', 'Saco da Ribeira', 'Ubatuba', 'SP');

-- BOATS
INSERT INTO boats (name, description, type, capacity, price_per_hour, photo_url, owner_id, address_id) VALUES
('Sea Ray 510', 'Luxuoso iate motorizado com cabines espaçosas e equipamentos modernos', 'Motor Yacht', 10, 350.00, 'https://example.com/sea-ray.jpg', 1, 1),
('Jeanneau 64', 'Veleiro de alto desempenho com design elegante e conforto premium', 'Sailing Yacht', 8, 280.00, 'https://example.com/jeanneau.jpg', 2, 2),
('Lagoon 42', 'Catamarã espaçoso ideal para grupos grandes e passeios em família', 'Catamaran', 12, 420.00, 'https://example.com/lagoon.jpg', 3, 3),
('Boston Whaler', 'Lancha rápida e estável, perfeita para pescaria e passeios rápidos', 'Center Console', 6, 180.00, 'https://example.com/boston.jpg', 4, 4),
('MasterCraft X26', 'Barco esportivo para wakeboard e esqui aquático com torre profissional', 'Ski Boat', 8, 220.00, 'https://example.com/mastercraft.jpg', 5, 5),
('Bayliner VR5', 'Barco versátil para dia de praia com amplo espaço de convés', 'Bowrider', 6, 150.00, 'https://example.com/bayliner.jpg', 1, 6),
('Beneteau 34', 'Veleiro clássico para experiências autênticas de navegação', 'Sailboat', 6, 200.00, 'https://example.com/beneteau.jpg', 2, 7),
('Yamaha 242X', 'Jet boat potente com sistema de direção dupla e som premium', 'Jet Boat', 8, 190.00, 'https://example.com/yamaha.jpg', 3, 8),
('Grady-White 30', 'Barco de pesca offshore com equipamentos profissionais', 'Center Console', 6, 210.00, 'https://example.com/grady.jpg', 4, 1),
('Nautique GS22', 'Barco de competição para esportes aquáticos com lastro ajustável', 'Ski Boat', 7, 230.00, 'https://example.com/nautique.jpg', 5, 2);

-- BOATS_AVAILABILITY
INSERT INTO boats_availability (boat_id, start_date, end_date) VALUES
(1, '2025-09-01 08:00:00', '2025-09-30 18:00:00'),
(2, '2025-09-01 09:00:00', '2025-09-28 17:00:00'),
(3, '2025-09-05 07:00:00', '2025-09-25 19:00:00'),
(4, '2025-09-10 08:30:00', '2025-09-20 16:30:00'),
(5, '2025-09-03 10:00:00', '2025-09-27 15:00:00');

-- BOOKINGS
INSERT INTO bookings (user_id, boat_id, start_date, end_date, status, total_price) VALUES
(1, 1, '2025-09-15 09:00:00', '2025-09-15 12:00:00', 'confirmed', 1050.00),
(2, 3, '2025-09-20 10:00:00', '2025-09-20 14:00:00', 'confirmed', 1680.00),
(3, 2, '2025-09-18 08:00:00', '2025-09-18 11:00:00', 'pending', 840.00),
(4, 5, '2025-09-22 13:00:00', '2025-09-22 16:00:00', 'confirmed', 660.00),
(1, 6, '2025-09-25 14:00:00', '2025-09-25 17:00:00', 'cancelled', 450.00);

-- REVIEWS
INSERT INTO reviews (user_id, boat_id, rating, comment, date) VALUES
(1, 1, 5, 'Experiência incrível! Equipamento impecável e equipe muito atenciosa.', NOW()),
(2, 3, 4, 'Barco espaçoso e confortável. Perfeito para nosso grupo de amigos.', NOW()),
(3, 2, 5, 'Veleiro maravilhoso! Dias de navegação inesquecíveis.', NOW()),
(4, 5, 3, 'Barco bom, mas poderia ter mais equipamentos de segurança.', NOW()),
(1, 6, 2, 'Problemas mecânicos durante o passeio. Decepcionante.', NOW());

--PAYMENTS
INSERT INTO payments (booking_id, amount, status, payment_date) VALUES
(1, 1050.00, 'completed', NOW()),
(2, 1680.00, 'completed', NOW()),
(3, 840.00, 'pending', NULL),
(4, 660.00, 'completed', NOW()),
(5, 450.00, 'refunded', NOW());

-- MESSAGES
INSERT INTO messages (booking_id, sender_id, content, sent_at) VALUES
(1, 1, 'Olá, gostaria de confirmar o horário do passeio de sábado.', NOW()),
(1, 5, 'Confirmado! Estaremos te esperando às 9h no píer.', NOW()),
(2, 2, 'Tem colete salva-vidas para crianças?', NOW()),
(2, 5, 'Sim, temos coletes de todos os tamanhos!', NOW()),
(3, 3, 'Precisamos adiar o passeio para a próxima semana.', NOW());


-- Change role to admin

UPDATE users
SET "role" = 'ROLE_ADMIN'
WHERE user_id = 1;